/*
Fibonacci - Фибоначи числа 0, 1, 1, 2, 3, 5, 8, 13...n (Сборът на всяка двойка числа е равен на следващото)

Exercise:
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms.By starting with 1 and 2, the first 10
terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
*/

using System;

public class Fibonacci
{
    public static void Main()
    {
        int limit = 4000000;
        int sum = 0;

        // Начална двойка числа от фибоначи
        int f1 = 0;
        int f2 = 1;

        while (f2 <= limit)
        {
            if (f2 % 2 == 0)
            {
                sum += f2;
            }

            // Ъпдейт на фибоначи двойката със следващата двойка
            int temp = f2;
            f2 = f1 + f2;
            f1 = temp;
        }

        Console.WriteLine("The sum of even Fibonacci numbers, numbers that are less than or equal to {0:N0}, is {1:N0}", limit, sum);
    }
}
